### ISSUE TITLE
How can I regenerate `defects4j-bugs.json`?

### ISSUE THREAD

**Issue by jose** [program-repair/defects4j-dissection#4]
Hi,

Any chance you could share the script / program you used to extract the repair actions in a D4J patch? I.e., the script you used to generate the `defects4j-bugs.json` file.

Thanks in advance.

**Comment by jose** [comment]
Just noticed you mentioned in the paper that the extraction of repair actions was performed manually.

**Comment by tdurieux** [comment]
You can look at https://github.com/lascam-UFU/automatic-diff-dissection
We did an automatization of this task.
