### ISSUE TITLE
What is the difference between Closure 92 and 93

### ISSUE THREAD

**Issue by DehengYang** [program-repair/defects4j-dissection#5]
According to the information given below and the detailed list shown in [program-repair.org/defects4j-dissection/#!/ ](program-repair.org/defects4j-dissection/#!/), it seems that there is no difference between Closure 92 and 93...

![image](https://user-images.githubusercontent.com/32570286/53961990-ebab2200-4124-11e9-9c1a-9de55cd580a7.png)
![image](https://user-images.githubusercontent.com/32570286/53962000-f4035d00-4124-11e9-9603-136ec7296470.png)

I am not sure whether I misunderstand the two bugs ... Any help would be much appreciated.

**Comment by victor-sobreira** [comment]
Hi DehengYang,
You are right about the duplication. We have reported this in Section Threats to Validity of our [paper](https://github.com/program-repair/defects4j-dissection/blob/master/2018.03.20%20-%20Defects4J%20Dissection%20-%20Oficial%20Pre-Print.pdf).
Cheers,
Victor.

**Comment by DehengYang** [comment]
Hi Victor,

Thank you for your prompt reply! I have found the corresponding information in the paper you offer. 

Thank you again for your guidance.

Best regards,
Deheng
